### ISSUE TITLE
Sharding

### ISSUE THREAD

**Issue by wolfcpp** [Hexicord/Hexicord#2]
Discord Sharding is a type of application partitioning that is used to divide bots into smaller, faster and more easily managed parts that are working as a separate logical processes. They can interract using the same methods as the "master" shard, except only the "master" shard receives direct messages.

**Comment by foxcpp** [comment]
Implemented in f8fc9d9c31241c1db2e507d9dee01e5e47a4d6fc, merged into `dev` branch, testing required.

**Comment by foxcpp** [comment]
@NamedKitten didn't wrote response, but he tested it actually. So we can assume it works as it should. Closing.
